### PR TITLE
Fix feature_gates

### PR DESCRIPTION
**Pull request by nicokratky**
Hi!

`feature_gates` and `runtime_config` are still broken.

The feature_gates map also had the same problem with the expected type as the runtime_config had. I also had to initialize the `RuntimeConfig` and `FeatureGates` maps of the kind resource, as otherwise go would complain about an assignment to an entry in a nil map.
The test cases were also wrong, as you changed the types of those two options to maps.

Feel free to edit/ask for any changes 😊

### CODE REVIEW

**Comment by tehcyx** [comment]
Great work, thanks. I had thought I covered it all. Running my tests again. And seems I also have to do some more fixes on PR tester...

**Comment by tehcyx** [comment]
Huh, I was not aware the test syntax is different for the map. TIL!

Btw if you have a suggestion to improve this part: https://github.com/tehcyx/terraform-provider-kind/blob/master/kind/structure_kind_config.go#LL47C16-L47C26

I'm not sure this is the best solution. I was hoping that with a map I could have a `"api/alpha"` key that is a string, but it seems HCL does not allow that.

**Comment by tehcyx** [comment]
Ran your code locally and it seems to be working fine. I also fixed the PR test runner (again) for the next PR to come in.

**Review by tehcyx — APPROVED** [review]

**Comment by nicokratky** [comment]
Hey! Thanks for merging this so quickly!

> Btw if you have a suggestion to improve this part: https://github.com/tehcyx/terraform-provider-kind/blob/master/kind/structure_kind_config.go#LL47C16-L47C26

I think that your solution is actually quite okay, that's a pretty unfortunate limitation of HCL in this case. My only recommendation would be to document this behavior, as it is not trivial that your provider will replace certain characters.

**Pull request merged**
