### PR TITLE
Add read only mount support

### PR DESCRIPTION
**Pull request by JackFlukinger**

### CODE REVIEW

**Comment by JackFlukinger** [comment]
Hey @tehcyx, anything else I need to do for this PR? Really appreciate your work on this provider!

**Comment by tehcyx** [comment]
Hi @JackFlukinger, no you're good. Just haven't gotten around testing this. Doing that now, as well as running tests on the PR.

**Comment by JackFlukinger** [comment]
Ah, I do see one small problem now that I look back. Oops!

**Comment by JackFlukinger** [comment]
Yeah, I just saw that, I think read_only is more idiomatic. I'll add propagation & selinux_relable real quick

**Comment by tehcyx** [comment]
> Yeah, I just saw that, I think read_only is more idiomatic. I'll add propagation & selinux_relable real quick
True. Thanks for adding the other two.

**Comment by JackFlukinger** [comment]
Cool, done, let me know if that looks all good to you :)

**Comment by tehcyx** [comment]
> Cool, done, let me know if that looks all good to you :)

Testing, then probably merging if nothing pops up.

**Pull request merged**
